removing using and data folder
KirilPecev/SoftServeWebApp pull request #1
Opened 2019-07-29 22:50 UTC by DKatsarski

2019-07-30 21:12 UTC, DKatsarski commented
The db is with localhost
Azure not yet implemented
Ef and its features installed though

2019-07-30 21:24 UTC, valiusa approved these changes

2019-07-30 21:27 UTC, KirilPecev commented
The WebApp.Web Data folder is useless instead, use -> WebAppDbContext in WebApp.Data. We do not need Models in WebApp.Data. All db models will be in WebApp.Domain.

2019-07-30 21:42 UTC, KirilPecev requested changes
The WebApp.Web Data folder is useless instead, use -> WebAppDbContext in WebApp.Data. We do not need Models in WebApp.Data. All db models will be in WebApp.Domain.
Create models for DB in WebApp.Domain and then use migration.

2019-07-31 09:06 UTC, KirilPecev approved these changes

2019-07-31 09:06 UTC, merged