The branch of dimitar
KirilPecev/SoftServeWebApp pull request #46
Opened 2019-08-08 17:30 UTC by DKatsarski

2019-08-08 18:40 UTC, IvayloGugalov commented on WebApp.Web/WebApp.Services/WebApp.Services.csproj
> +    <ProjectReference Include="..\WebApp.Data\WebApp.Data.csproj" />
не съм сигурен дали референцията ще се открие от другите

2019-08-08 18:40 UTC, IvayloGugalov approved these changes

2019-08-08 19:08 UTC, IvayloGugalov requested changes
changes

2019-08-09 10:46 UTC, GGeorgiew988 approved these changes

2019-08-09 11:06 UTC, valiusa approved these changes

2019-08-10 12:51 UTC, closed without merging